### ISSUE TITLE
Add custom ip lists & fields in threat-detection System->Configurations

### ISSUE THREAD

**Issue by ion-storm** [graylog-labs/graylog-plugin-threatintel#36]
Please allow us to add custom threat detection lists for IP's from any location like:
http://www.openbl.org/lists/base.txt
And also pull from github locations like this:
https://github.com/StevenBlack/hosts

**Comment by lennartkoopmann** [comment]
This will be solved with generic lookup tables in the next major Graylog release! :)

See #19
