### ISSUE TITLE
Not installed on graylog-2.2.1-1

### ISSUE THREAD

**Issue by gitty8** [graylog-labs/graylog-plugin-threatintel#42]
Hi, I downloaded last release to /opt/graylog/plugin and restarted the VM.
If check at /system/configurations the plugin doesnt appear as installed.
Can anyone assist?

https://i.imgur.com/rCE4qf9.png

**Comment by joschi** [comment]
@gitty8 This plugin is not shipped with Graylog. You need to install it: http://docs.graylog.org/en/2.2/pages/configuration/graylog_ctl.html#install-graylog-plugins

**Comment by joschi** [comment]
Ah, sorry. I misread that.

**Comment by joschi** [comment]
@gitty8 Please post the output of `ls -la /opt/graylog/plugin` and the logs of your Graylog node (see http://docs.graylog.org/en/2.2/pages/configuration/file_location.html for their location)

**Comment by gitty8** [comment]
```
root@graylog:~# ls -la /opt/graylog/plugin/
total 19212
drwxr-xr-x  2 root root    4096 Apr 19 07:59 .
drwxr-xr-x 12 root root    4096 Feb 20 14:19 ..
-rw-r--r--  1 root root  499210 Feb 20 14:01 graylog-plugin-anonymous-usage-statistics-2.2.1.jar
-rw-r--r--  1 root root   27030 Feb 20 14:01 graylog-plugin-beats-2.2.1.jar
-rw-r--r--  1 root root 2935745 Feb 20 14:01 graylog-plugin-collector-2.2.1.jar
-rw-r--r--  1 root root 4132492 Feb 20 14:01 graylog-plugin-enterprise-integration-2.2.1.jar
-rw-r--r--  1 root root 6483651 Feb 20 14:01 graylog-plugin-map-widget-2.2.1.jar
-rw-r--r--  1 root root 5581585 Feb 20 14:01 graylog-plugin-pipeline-processor-2.2.1.jar
-rw-r--r--  1 root root       0 Feb 23 11:48 graylog-plugin-threatintel-0.10.0.jar
root@graylog:~# 
```

**Comment by joschi** [comment]
@gitty8 The JAR file is empty (0 bytes). Make sure to download the plugin correctly.
