### ISSUE TITLE
IP whois Lookup Rule Source Not Working

### ISSUE THREAD

**Issue by GTownson** [graylog-labs/graylog-plugin-threatintel#44]
let whois_intel = whois_lookup_ip(to_string($message.DstIP), "DstIP")
 set_fields(whois_intel);

When using these two lines in my rule source it throws up an error on the second line which is:
![github error](https://cloud.githubusercontent.com/assets/28807776/26250939/97f769b6-3ca3-11e7-8b6a-b09f1fa3b45a.jpg)

These two lines of source rule were copied from the plugins GitHub page so in theory should work.

**Comment by kroepke** [comment]
You need a semicolon at the end of the line :)

**Comment by GTownson** [comment]
Ah thankyou kroepke!
