### ISSUE TITLE
Unknown function error

### ISSUE THREAD

**Issue by renjith1234** [graylog-labs/graylog-plugin-threatintel#46]
While creating a rule using threat intel it is showing error unknown function. I am using graylog server version 2.2.3-1

**Comment by joschi** [comment]
@renjith1234 How did you install and configure Graylog?
How did you download, install, and configure the Threat Intelligence plugin?
Do you see the Threat Intelligence plugin in the log output of your Graylog node on startup?

**Comment by renjith1234** [comment]
Graylog server is a single node installation. Threat plugin installed using debian package.
Plugin is loading at the time server starts.I can see that in the log. Also in graylog dashboard under configuration section I have enabled every lookups ,that is OTX,tor,whois,etc. But when I create rule its showing error.

**Comment by renjith1234** [comment]
![image](https://user-images.githubusercontent.com/7067109/27863861-16fbc41e-619d-11e7-9f2a-3475304c87c1.png)

**Comment by joschi** [comment]
@renjith1234 Please post the rule which triggers the error.
Also please post the content of the "Installed plugins" section on the *System* / *Nodes* / *Details* page.

> Graylog server is a single node installation.

Please provide more details. Is this a manual install, an installation from the official packages (DEB or RPM), or an OVA?
What's in your Graylog configuration file?

**Comment by renjith1234** [comment]
This is a manual basic installation of graylog server following the installation guide for ubuntu server in graylog documentation. Nothing changed in configuration file other than the required changes as per the installation guide.

**Comment by renjith1234** [comment]
![image](https://user-images.githubusercontent.com/7067109/27864934-a51aea78-61a1-11e7-9f59-d46bdc3ce294.png)
Installed plugins

**Comment by joschi** [comment]
@renjith1234 You're using an old version of the Pipeline Processor plugin which might be incompatible with your version of Graylog or the version of the Threat Intelligence plugin.

 Please post the rule which triggers the error.

**Comment by renjith1234** [comment]
Pipeline processor plugin came with the graylog latest version 2.2.3-1 installation.

Rule:

rule "Threat Intel Lookup SourceAddress"
when
    has_field("SourceAddress")
then
    let src_addr_intel = threat_intel_lookup_ip(to_string($message.SourceAddress), "SourceAddress");
    set_fields(src_addr_intel);
end

**Comment by joschi** [comment]
> Pipeline processor plugin came with the graylog latest version 2.2.3-1 installation.

That's not true, at least for any of the official release artifacts (tar balls, OS packages (DEB/RPM), Docker images, OVA/AMI).

Check the plugin directory of your Graylog node for some stale files.

**Comment by renjith1234** [comment]
![image](https://user-images.githubusercontent.com/7067109/27868133-d8fd362e-61ac-11e7-8f03-fbab09338a61.png)
Installed jar is showing version 2.2.3 but in the details it is 2.2.0

**Comment by joschi** [comment]
@renjith1234 Nope, it's using the version from the Maven POM, i. e. "2.2.3", so there's definitely something fishy with your plugins.

* https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/2.2.3/plugin/src/main/java/org/graylog/plugins/pipelineprocessor/PipelineProcessorMetaData.java#L55
* https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/2.2.3/plugin/src/main/resources/org.graylog.plugins.graylog-plugin-pipeline-processor/graylog-plugin.properties#L2
* https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/2.2.3/plugin/pom.xml#L16

**Comment by joschi** [comment]
I also failed to reproduce the issue with a fresh installation of Graylog 2.2.3 with the Threat Intelligence plugin 0.10.0, so I'm closing this issue now.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by renjith1234** [comment]
Thanks for the support

**Comment by renjith1234** [comment]
Identified the cause of the issue. Threat intel plugin is not compatible with CEF input plugin version 1.2.0 .

I tried with the previous version of CEF plugin and now it is working.
